"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

The "scitex-dev installed" gate lives in a `pytest.mark.skipif`
decorator (`skipif` is not an assertion), so the body keeps a single
bare `assert` (mirrors scitex-scholar).
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

# The checkout this test file lives in: tests/develop/test_audit.py -> repo
# root. Passed to `audit_all_for_package` so the gate grades THIS tree.
_REPO_ROOT = Path(__file__).resolve().parents[2]


@pytest.mark.skipif(
    shutil.which("scitex-dev") is None,
    reason=(
        "scitex-dev not installed — add `scitex-dev[cli-audit]` "
        "to [project.optional-dependencies.dev]"
    ),
)
def test_audit_all_clean():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    completed = False
    # Act
    audit_all_for_package("scitex-stats", path=_REPO_ROOT, skip_rules=("PA-307",))
    completed = True
    # Assert
    assert completed
